Tags Detection tags.cs
TagsApi exists and is functioning properly.
TagsApi plugin does not exist (catching KeyNotFoundException).
Other exceptions occurred while retrieving TagsApi.


ERORR LOG:
```03:27:54 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.Collections.Generic.KeyNotFoundException: The given key 'tags:api' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at Store.Item_Tags.OnPluginsAllLoaded() in C:\Users\Administrator\source\repos\cs2-store\Store\src\item\items\tags.cs:line 42
   at Store.Store.OnAllPluginsLoaded(Boolean hotReload) in C:\Users\Administrator\source\repos\cs2-store\Store\src\cs2-store.cs:line 86
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106```